### ISSUE TITLE
bdist_utils deprecation, removal Python 3.12

### ISSUE THREAD

**Issue by agirault** [karellen/wheel-axle#10]
Do you have any plans for the upcoming removal of `bdist_utils` ?

**Comment by arcivanov** [comment]
What is "bdist_utils"? I'm fairly certain it [does not exist](https://www.google.com/search?sxsrf=AJOqlzWUnOveXkHQK2cwvevbGj5lDOEqEA:1678745936106&q=%22bdist_utils%22&nfpr=1&sa=X&ved=2ahUKEwjf_8H599n9AhVsk4kEHfJ5B04QvgUoAXoECAgQAg&biw=1920&bih=936&dpr=1).

Do you mean "distutils" deprecation?  We rely heavily on `setuptools` which are not deprecated. Do you have any specific concerns after trying on Python 3.12 beta?

**Comment by arcivanov** [comment]
@agirault The Python 3.12a6 seems to be working fine.

https://github.com/karellen/wheel-axle/pull/11/checks

**Comment by arcivanov** [comment]
@agirault any feedback?

**Comment by arcivanov** [comment]
Please reopen if you have specific concerns about CP 3.12 - I haven't found any issues and the tests pass.

**Comment by agirault** [comment]
Thank you, sorry for going AWOL on this, was pulled on other things

**Comment by arcivanov** [comment]
@agirault no worries. But is it an issue that you observed or were you just inquiring in a precautionary manner?
