### ISSUE TITLE
`[Errno 17] File exists` error for nested symlinks of package data

### ISSUE THREAD

**Issue by agirault** [karellen/wheel-axle#12]
Say this is in a setup.py to copy C++ shared libraries to a python wheel:

```py
    include_package_data=True,
    package_dir={
        "mypackage/lib": "cmake_install/cpp_libs",
    },
    package_data={
        "mypackage/lib": ["*.so*", "**/*.so*"],
    },
```

`cmake_install/cpp_libs` could have libraries of this form, captured by the second regex:
- `prefix/foo.so`, which links to...
- `prefix/foo.so.0`, which links to...
- `prefix/foo.so.0.1`

Because of the `prefix` directory in the path, the `data_files` in `wheel_axle.bdist_axle.BuildPy.build_package_data` ([here](https://github.com/karellen/wheel-axle/blob/master/src/main/python/wheel_axle/bdist_axle/__init__.py#L153)) have duplicate copy commands:
- in package `install/cpp_libs`: `prefix/libfoo.so*` files
- in package `install/cpp_libs.prefix` : `libfoo.so*` files (without the `prefix` directory).

When calling [`BuildPy.copy_file`](https://github.com/karellen/wheel-axle/blob/master/src/main/python/wheel_axle/bdist_axle/__init__.py#L158), non-symlinks (like `prefix/libfoo.so.0.1`) are handled fine since [`super().copy_file`](https://github.com/karellen/wheel-axle/blob/master/src/main/python/wheel_axle/bdist_axle/__init__.py#L172-L174) handles it gracefully (no error, just returns `false` in the return value for "not copied" if it already exists).

However, symlinks (like `prefix/foo.so.0` and `prefix/foo.so`) are handled by [`copy_link`](https://github.com/karellen/wheel-axle/blob/master/src/main/python/wheel_axle/bdist_axle/__init__.py#L169) which [seems to assume always doing the copy](https://github.com/karellen/wheel-axle/blob/master/src/main/python/wheel_axle/bdist_axle/__init__.py#L170). Due to the duplicate copies from the separate packages listed above, the second copy fails with the following error:
```
error: [Errno 17] File exists: 'libfoo.so.0' -> './mypackage/lib/prefix/libfoo.so'
```

**Comment by agirault** [comment]
Looking deeper at `super.copy_file` which seems to work, it's calling the `setuptools.build_py` definition which in turn calls the `distutils.file_util.copy_file` one.

In there, there is a check: https://github.com/pypa/distutils/blob/main/distutils/file_util.py#L157
```py
if not (os.path.exists(dst) and os.path.samefile(src, dst)):
```

which we probably want here: https://github.com/karellen/wheel-axle/blob/b13e8152db76d1dddea68c29c3953b6b39d1c17a/src/main/python/wheel_axle/bdist_axle/_file_utils.py#L40-L41

----

Though after digging into this, I'm actually wondering why we don't instead override `build_py.copy_file` to pass `link="sym"` if `os.path.islink(infile)`.

**Comment by arcivanov** [comment]
Thanks for the report. How urgent is this? I will be AWOL for the next few days on the family stuff that is an absolutely priority unfortunately.

**Comment by arcivanov** [comment]
Could you also provide a reproducible setup.py case with the files? Files don't have to be real, could be zero-length.

**Comment by agirault** [comment]
> Thanks for the report. How urgent is this? I will be AWOL for the next few days on the family stuff that is an absolutely priority unfortunately.

Never as urgent as family stuff, especially for a free open-source project :) Mostly a report for when is convenient to you, I'll find another solution or patch in the meantime.

**Comment by agirault** [comment]
Provided a fix in #13

**Comment by arcivanov** [comment]
I fixed the issue with a reproducible case in #14. Please test with `pip install -U --pre wheel-axle`.

**Comment by arcivanov** [comment]
@agirault once you establish that the fix is working for you, I'll release the new version. Thanks!

**Comment by arcivanov** [comment]
@agirault bump

**Comment by arcivanov** [comment]
@agirault another bump :smile:
